#! /bin/sh

killall mpd &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV
bspc monitor HDMI-1 -d V VI

bspc config border_width         2
bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Alacritty state=floating

# border colors
bspc config focused_border_color "#83a598"
bspc config normal_border_color "#454849"

compton &
dunst &
mpd &
setxkbmap -option caps:super &
feh --bg-fill $HOME/workspace/dotfiles/wallpapers/saitama-ok.png &
$HOME/.config/polybar/launch.sh
