#! /bin/sh
killall mpd &
killall picom &

#Configs side of monitors BSPWM
SECOND_MONITOR_SIDE="left"
THIRD_MONITOR_SIDE="right"

#Get Monitors
PRINCIPAL=$(xrandr | grep primary | awk '{print $1}')
SECOND_MONITOR=$(xrandr | grep connected | awk '{i++}i==2'| awk '{print $1}')
THIRD_MONITOR=$(xrandr | grep connected | awk '{i++}i==3'| awk '{print $1}')

sxhkd &

 #Configure Monitors
if [ "$(xrandr | grep -sw 'connected' | wc -l)" = "3" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
  bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII VIII IX X
  bspc monitor $(bspc query -M | sed -n 3p) -d XI XII XIII XIV XV
   # Set Monitors Side and output
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
  xrandr --output $THIRD_MONITOR --$THIRD_MONITOR_SIDE-of $PRINCIPAL
elif [ "$(xrandr | grep -sw 'connected' | wc -l)" = "2" ]; then
  bspc monitor $(bspc query -M | sed -n 1p) -d I II III IV
  bspc monitor $(bspc query -M | sed -n 2p) -d V VI VII VIII IX X
  #Set Monitors Side and output
  xrandr --output $SECOND_MONITOR --$SECOND_MONITOR_SIDE-of $PRINCIPAL
else
  bspc monitor -d I II III IV V
fi

# bspc monitor -d I II III IV
# bspc monitor HDMI-1 -d V VI

bspc config border_width         2
bspc config window_gap          12

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# move and resize window with mouse
bspc config pointer_mod         mod4
bspc config pointer_action1     move
bspc config pointer_action2     resize_side
bspc config pointer_action3     resize_corner
bspc config pointer_motion_interval 0
bspc config honor_size_hints true
# bspc config ignore_ewh_struts polybar-msg

bspc rule -a '*:*:Picture in picture' state=floating

# bspc rule -a TelegramDesktop desktop='^5' follow=on border=off state=tiled
# bspc rule -a Skype desktop='^5' follow=on border=off state=tiled
bspc rule -a Slack desktop='^5' follow=on border=off state=tiled
bspc rule -a zoom desktop='^6' state=tiled center=on follow=on border=off

bspc rule -a flameshot state=floating
# bspc rule -a Ulauncher state=floating

# border colors
bspc config normal_border_color "#3b3f4c"
bspc config active_border_color "#777777"

bspc config focused_border_color '#296596'

bspc config presel_feedback_color "#6272a4"

picom -b --config ~/.config/picom.conf &
dunst &
mpd &
cmst --minimized --wait-time 5 &
setxkbmap -option caps:escape &
feh --bg-fill $HOME/workspace/dotfiles/wallpapers/asta.jpg &
$HOME/.config/polybar/launch.sh &
$HOME/workspace/dotfiles/scripts/setup-xinput.sh &
xsetroot -cursor_name left_ptr &
